### ISSUE TITLE
iframe跨域问题

### ISSUE THREAD

**Issue by liufuhu** [genify/nej#18]
阅读NEJ源码后，我对iframe跨域通信有点疑问。
低版本浏览器中，NEJ借助iframe进行跨域通信。 它通过iframe的name作为传输媒介，采用定时器检测 iframe name的改变实现数据传输。 假设 ```a.com/b.html``` 往 ```c.com``` 发送数据，首先在 ```c.com``` 的服务器上放 ```nej_proxy_frame.html``` 这个文件，然后在 ```a.com/b.html``` 里把iframe的src设置为： ```c.com/res/nej_proxy_frame.html```。 ```nej_proxy_frame.html``` 中会定时检测 ```window.name```，当有数据要传给 ```a.com/b.html```时会修改```parent.name```；同理 ```a.com/b.html``` 会通过定时器检测```window.name```和设置iframe name的变化实现数据传输。  
这里有个问题是：在 ```a.com/b.html``` 里对 iframe.contentWindow.name进行赋值，会由于同源策略的安全限制抛出错误吧？  
我自己做了个实验，本地通过域名绑定和Nginx代理启动了两个服务：a.com和b.com。在chrome浏览器中，把```NEJ base/platform.js```中的 ```_kernel.engine``` 和 ```_kernel.engine``` 分别设置为： trident和2.0；```window.postMessage```设置为null。 在a.com下向b.com发送数据，会报错：
``` Uncaught DOMException: Blocked a frame with origin "http://www.b.com" from accessing a cross-origin frame. ```
低版本下IE下，不会有这个问题吗？抑或是其他问题，期盼解答，谢谢飞哥~

**Comment by genify** [comment]
非常感谢虎哥的细致分析，window.name 的队列轮询处理只会在IE7及以下版本的浏览器里生效，这部分浏览器还没有开始做此类的安全限制，也有的方案会借助浏览器 navigator 下方法的跨域调用的漏洞来实现

**Comment by liufuhu** [comment]
@genify got it！谢谢飞哥~
